### ISSUE TITLE
Error decoding client data

### ISSUE THREAD

**Issue by ilCapo01** [rune-js/server#146]
[1] Error decoding client data
[1] TypeError: this[methodName] is not a function
[1]     at ByteBuffer.put (server\node_modules\@runejs\byte-buffer\src\byte-buffer.ts:95:29)
[1]     at LoginHandshakeParser.parse (server\src\net\data-parser\login-handshake-parser.ts:21:26)
[1]     at ClientConnection.parseIncomingData (server\src\net\client-connection.ts:51:33)
[1]     at Socket.socket.on.data (server\src\game-server.ts:110:38)
[1]     at Socket.emit (events.js:189:13)
[1]     at addChunk (_stream_readable.js:284:12)
[1]     at readableAddChunk (_stream_readable.js:265:11)
[1]     at Socket.Readable.push (_stream_readable.js:220:10)
[1]     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

I'm using "refactored-client-435" to connect.

**Comment by Promises** [comment]
Did you change the supplied rsa keys?

**Comment by ilCapo01** [comment]
Yeah, i did. 
https://pastebin.com/Jj09UATK
https://pastebin.com/rxd7aiGC

**Comment by Promises** [comment]
Seems like you used the public keys on the server, that's supposed to be private keys, I recommend you test with the default ones to verify it works

**Comment by TheBlackParade** [comment]
Looks like it's been awhile, so I'll consider this closed. Feel free to submit another ticket or give us a shout on Discord if you continue to experience issues.
