### ISSUE TITLE
[BUG] Default item spawn bug

### ISSUE THREAD

**Issue by hallowatcher** [rune-js/server#292]
**Describe the bug**
If you move far enough away from a default item spawn, it will throw the following out of range exception:
![image](https://user-images.githubusercontent.com/6265839/114478123-e5d67380-9bfd-11eb-9096-d4ca3dc3dd10.png)

**To Reproduce**
1. Go to the wilderness
2. Log out
3. Log back in

**Expected behavior**
No error should be thrown

**Desktop (please complete the following information):**
 - OS: Windows 10

Here's a video of it happening, right on the chunk where it breaks:
[Video](https://hwc.hr/i/pCVZDqXh.mp4)

From what I dug up, it seems to be this calculation that is generating an out of range X and Y (outbound-packets.ts)
![image](https://user-images.githubusercontent.com/6265839/114478522-b6743680-9bfe-11eb-9a9a-17eb4a4a3c91.png)

Maybe such items shouldn't spawn for the player instance when they are so far away?

**Comment by Jameskmonger** [comment]
Can confirm this is still an issue

**Comment by gruckion** [comment]
In case anyone else is searching for this issue

```
[2] [2022-09-07T15:02:25.898Z] ERROR (5468 on Sigexs-MBP.broadband): The value of "value" is out of range. It must be >= 0 and <= 255. Received 583
[2]     RangeError: The value of "value" is out of range. It must be >= 0 and <= 255. Received 583
[2]         at new NodeError (node:internal/errors:371:5)
[2]         at writeU_Int8 (node:internal/buffer:738:11)
[2]         at Packet.writeUInt8 (node:internal/buffer:748:10)
[2]         at Packet.put (/Users/sigex/workdir/rsps/server/node_modules/@runejs/src/buffer/byte-buffer.ts:158:40)
[2]         at OutboundPacketHandler.updateReferencePosition (/Users/sigex/workdir/rsps/server/src/engine/net/outbound-packet-handler.ts:228:16)
[2]         at OutboundPacketHandler.setWorldItem (/Users/sigex/workdir/rsps/server/src/engine/net/outbound-packet-handler.ts:181:14)
[2]         at WorldInstance.spawnWorldItem (/Users/sigex/workdir/rsps/server/src/engine/world/instances.ts:132:39)
[2]         at forEach (/Users/sigex/workdir/rsps/server/src/engine/world/world.ts:370:30)
[2]         at Array.forEach (<anonymous>)
[2]         at World.spawnWorldItems (/Users/sigex/workdir/rsps/server/src/engine/world/world.ts:367:14)
```

**Comment by DrJacobHolden** [comment]
Still an issue - you can reproduce it also by dropping items, logging out and then logging back in.
