### ISSUE TITLE
Can not get the server running

### ISSUE THREAD

**Issue by mitchngwen** [rune-js/server#311]
Hi i have spent hours trying to get this to work, I just can not seem to get the server running. Any help would be awesome as I would like to play this with my family. Below is the code from my terminal:

mitch@pop-os:~/Documents/server-develop$ npm start

> @runejs/server@1.0.0-alpha.0 start
> npm run build && concurrently "npm run build:watch" "npm run start:infra" "npm run start:game"

> @runejs/server@1.0.0-alpha.0 build
> rimraf dist && babel ./src --out-dir dist --extensions ".ts,.tsx,.js" --source-maps

Successfully compiled 242 files with Babel (5903ms).
[2] 
[2] > @runejs/server@1.0.0-alpha.0 start:game
[2] > nodemon --delay 5000ms --max-old-space-size=2048 dist/index.js
[2] 
[1] 
[1] > @runejs/server@1.0.0-alpha.0 start:infra
[1] > concurrently "npm run start:update" "npm run start:login"
[1] 
[0] 
[0] > @runejs/server@1.0.0-alpha.0 build:watch
[0] > babel ./src --out-dir dist --extensions ".ts,.tsx,.js" --source-maps --watch
[0] 
[2] [nodemon] 2.0.6
[2] [nodemon] reading config ./nodemon.json
[2] [nodemon] to restart at any time, enter `rs`
[2] [nodemon] or send SIGHUP to 53580 to restart
[2] [nodemon] ignoring: ./src/plugins/**/*
[2] [nodemon] watching path(s): src/**/*
[2] [nodemon] watching extensions: ts,js
[2] [nodemon] starting `node --max-old-space-size=2048 dist/index.js`
[2] [nodemon] spawning
[2] [nodemon] child pid: 53608
[2] [nodemon] watching 129 files
[2] node:internal/modules/cjs/loader:1168
[2]   return process.dlopen(module, path.toNamespacedPath(filename));
[2]                  ^
[2] 
[2] Error: /home/mitch/Documents/server-develop/node_modules/canvas/build/Release/libcairo.so.2: cannot read file data
[2]     at Object.Module._extensions..node (node:internal/modules/cjs/loader:1168:18)
[2]     at Module.load (node:internal/modules/cjs/loader:989:32)
[2]     at Function.Module._load (node:internal/modules/cjs/loader:829:14)
[2]     at Module.require (node:internal/modules/cjs/loader:1013:19)
[2]     at require (node:internal/modules/cjs/helpers:93:18)
[2]     at Object.<anonymous> (/home/mitch/Documents/server-develop/node_modules/canvas/lib/bindings.js:3:18)
[2]     at Module._compile (node:internal/modules/cjs/loader:1109:14)
[2]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
[2]     at Module.load (node:internal/modules/cjs/loader:989:32)
[2]     at Function.Module._load (node:internal/modules/cjs/loader:829:14) {
[2]   code: 'ERR_DLOPEN_FAILED'
[2] }
[2] [nodemon] app crashed - waiting for file changes before starting...
[1] [1] 
[1] [1] > @runejs/server@1.0.0-alpha.0 start:login
[1] [1] > node --max-old-space-size=1024 dist/game-engine/login-server.js
[1] [1] 
[1] [0] 
[1] [0] > @runejs/server@1.0.0-alpha.0 start:update
[1] [0] > node --max-old-space-size=1024 dist/game-engine/update-server.js
[1] [0] 
[1] [0] node:internal/modules/cjs/loader:1168
[1] [0]   return process.dlopen(module, path.toNamespacedPath(filename));
[1] [0]                  ^
[1] [0] 
[1] [0] Error: /home/mitch/Documents/server-develop/node_modules/canvas/build/Release/libcairo.so.2: cannot read file data
[1] [0]     at Object.Module._extensions..node (node:internal/modules/cjs/loader:1168:18)
[1] [0]     at Module.load (node:internal/modules/cjs/loader:989:32)
[1] [0]     at Function.Module._load (node:internal/modules/cjs/loader:829:14)
[1] [0]     at Module.require (node:internal/modules/cjs/loader:1013:19)
[1] [0]     at require (node:internal/modules/cjs/helpers:93:18)
[1] [0]     at Object.<anonymous> (/home/mitch/Documents/server-develop/node_modules/canvas/lib/bindings.js:3:18)
[1] [0]     at Module._compile (node:internal/modules/cjs/loader:1109:14)
[1] [0]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
[1] [0]     at Module.load (node:internal/modules/cjs/loader:989:32)
[1] [0]     at Function.Module._load (node:internal/modules/cjs/loader:829:14) {
[1] [0]   code: 'ERR_DLOPEN_FAILED'
[1] [0] }
[1] [0] npm run start:update exited with code 1
[1] [1] [2021-05-12T05:26:40.415Z] INFO (53647 on pop-os): Login Server listening @ 0.0.0.0:43591.
[0] Successfully compiled 242 files with Babel (6123ms).

**Comment by src52** [comment]
Hello,

I haven't seen an error like this before, but you could try to do a fresh re-install of the packages by deleting the `node_modules` folder, and running `npm install` from that directory. I'd be interested in seeing if it has any problems there.

**Comment by mitchngwen** [comment]
That was the Trick! Thank you very much for your help!

**Comment by Tynarus** [comment]
Gonna close this as it was resolved. :)
